# Generated by Django 6.0.4 on 2026-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('end', 'End Device')], max_length=10)),
                ('network', models.CharField(choices=[('employee', 'Employee'), ('management', 'Management')], max_length=15)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning')], max_length=10)),
                ('ssh_enabled', models.BooleanField(default=False)),
                ('firewall_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
